apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-353217 
  artifacts:
    - image: islamahmed93/auth
    # - image: us.gcr.io/ticketing-dev-353217/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: islamahmed93/tickets
    # - image: us.gcr.io/ticketing-dev-353217/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: islamahmed93/orders
    # - image: us.gcr.io/ticketing-dev-353217/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: islamahmed93/client
    # - image: us.gcr.io/ticketing-dev-353217/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .